make clean
make compile
make run_cli GEN_TYPE=i2cmb_generator_direct_test TEST_SEED=random
make run_cli GEN_TYPE=i2cmb_generator_random_test TEST_SEED=random
make run_cli GEN_TYPE=i2cmb_generator_register_test TEST_SEED=random
make run_cli GEN_TYPE=i2cmb_generator_control_functionality_test TEST_SEED=random
make merge_coverage
make view_coverage
